### ISSUE TITLE
ME Wireless Transceiver crash (reproduceable)

### ISSUE THREAD

**Issue by minifid** [the9grounds/AE-Additions#117]
**Issue:** Game crashes whenever you open the gui for the Me Wireless Transceiver.
**MC Version:** 1.19.2
**Forge:** 43.2.3
**ATM8 Version:** 1.0.10
**AE2 Version:** 12.9.2
**AE Additions Version:** 4.0.2
**Steps to Reproduce:** 
1. Create an ae network that uses the Wireless transceiver to pass channels
2. Delete the Channel that is actively passing ae2 channels
3. Close the gui and reopen it (weirdly enough, I had to reopen it twice in my tests)

All my tests have been done on private channels, and on my single player world I was using to test, just launching the game again fixed the issue, so in a server setting, restarting the server will likely fix the issue.

I realize there are several other tickets that seem to have this same issue, but none of them seem to have steps to reproduce. If i handled this incorrectly I apologize.

**Comment by EnforcerTTV** [comment]
I also have the same issue

**Comment by TarantelTM** [comment]
Should fixed in 4.0.3.
But we get this Problem in 4.0.3 in 1.19.2 of ATM8 again.
At the begin no Problem but i was the only Player who use this and now a second player start using it and now we got this crashes.
Sometimes u get only a timeout for nullpointerexception and sometimes a complete client crash.

Crash Report: https://gist.github.com/TarantelTM/266b680578838b7ff656b58733a03a14

**Comment by wolflord212312** [comment]
Can confirm this is still a issue

**Comment by wolflord212312** [comment]
But if this happens on a server it is not fixed till server reboot

**Comment by wolflord212312** [comment]
You wont be able to open a wireless transceiver again till the reboot

**Comment by Beachman4** [comment]
I uploaded a new version to curseforge, can you see if you still have issues now?
